### ISSUE TITLE
这个插件支持v2.1的吗？

### ISSUE THREAD

**Issue by ilostycom** [maizuo-suda/yapi-plugin-import-postman2#2]
RT.

**Comment by ilostycom** [comment]
```
[error] ./client/index.js
Module parse failed: /usr/lib/node_modules/yapi-cli/src/commands/my-yapi/vendors/client/index.js Unexpected token (17:2)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (17:2)
    at Parser.pp$4.raise (/usr/lib/node_modules/ykit/node_modules/webpack/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/usr/lib/node_modules/ykit/node_modules/webpack/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp$3.parseExprAtom (/usr/lib/node_modules/ykit/node_modules/webpack/node_modules/acorn/dist/acorn.js:1822:12)
    at Parser.pp$3.parseExprSubscripts (/usr/lib/node_modules/ykit/node_modules/webpack/node_modules/acorn/dist/acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (/usr/lib/node_modules/ykit/node_modules/webpack/node_modules/acorn/dist/acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (/usr/lib/node_modules/ykit/node_modules/webpack/node_modules/acorn/dist/acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (/usr/lib/node_modules/ykit/node_modules/webpack/node_modules/acorn/dist/acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (/usr/lib/node_modules/ykit/node_modules/webpack/node_modules/acorn/dist/acorn.js:1597:21)
    at Parser.pp$3.parseExprList (/usr/lib/node_modules/ykit/node_modules/webpack/node_modules/acorn/dist/acorn.js:2165:22)
    at Parser.pp$3.parseSubscripts (/usr/lib/node_modules/ykit/node_modules/webpack/node_modules/acorn/dist/acorn.js:1741:35)
    at Parser.pp$3.parseExprSubscripts (/usr/lib/node_modules/ykit/node_modules/webpack/node_modules/acorn/dist/acorn.js:1718:17)
    at Parser.pp$3.parseMaybeUnary (/usr/lib/node_modules/ykit/node_modules/webpack/node_modules/acorn/dist/acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (/usr/lib/node_modules/ykit/node_modules/webpack/node_modules/acorn/dist/acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (/usr/lib/node_modules/ykit/node_modules/webpack/node_modules/acorn/dist/acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (/usr/lib/node_modules/ykit/node_modules/webpack/node_modules/acorn/dist/acorn.js:1597:21)
    at Parser.pp$3.parseExpression (/usr/lib/node_modules/ykit/node_modules/webpack/node_modules/acorn/dist/acorn.js:1573:21)
 @ multi index.js

编译客户端成功，请重启服务器
```

这种情况可能忽略吗。
